version: "3"

services:
  web:
    container_name: web
    image: php:7.4-apache
    ports:
      - 80:80
    volumes:
      - ./src/:/var/www/html/
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:8.0
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - default
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    links:
      - db 